version: '3.8'

services:
  app:
    image: my_http_server   
    build:
      context: .
    ports:
      - "5000"  
    deploy:
      replicas: 2  
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"
      restart_policy:
        condition: on-failure

  reverse-proxy:
    image: nginx:latest   
    ports:
      - "8080:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  

