apiVersion: v1
kind: Service
metadata:
  name: http-server-service
  labels:
    app: http-server
spec:
  type: LoadBalancer  
  ports:
  - port: 8080
    targetPort: 5000  
  selector:
    app: http-server
